name: Publish

on:
  workflow_dispatch: 
    inputs: 
      version:
        description: 'Version to publish'
        required: true
    
permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest

    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.ONIONFRUIT_TEAM_CLIENT_ID }}
          private-key: ${{ secrets.ONIONFRUIT_TEAM_CLIENT_KEY }}

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          token: ${{ steps.app-token.outputs.token }}
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}

  build-windows:
    name: Build (${{ matrix.rid }})
    runs-on: windows-latest
    environment: release

    needs: [create-draft-release]

    strategy:
      matrix:
        rid: [win-x64]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - id: import-cert
        name: Import Code Signing Certificate
        shell: pwsh
        run: |
          $data = [System.Convert]::FromBase64String($env:CertificateContents)
          $path = [System.IO.Path]::Combine($env:RUNNER_TEMP, 'certificate.pfx')
          
          Set-Content -Path $path -Value $data -AsByteStream
          echo "certPath=$path" >> $env:GITHUB_OUTPUT
        env:
          CertificateContents: ${{ secrets.CODESIGN_CERTIFICATE }}

      - id: deploytool
        name: Download Deployment Tool
        shell: pwsh
        env:
           GH_TOKEN: ${{ github.token }}
        run: |
          $zipPath = [System.IO.Path]::Combine($env:TEMP, 'onionfruit-deploy.zip')
          $deployToolHome = [System.IO.Path]::Combine($env:TEMP, 'onionfruit-deploy')
          
          Invoke-WebRequest -Uri https://github.com/dragonfruitnetwork/onionfruit-deploy/releases/download/1.1.1/onionfruit-deploy.zip -OutFile $zipPath
          gh attestation verify $zipPath --repo dragonfruitnetwork/onionfruit-deploy --deny-self-hosted-runners
          
          Expand-Archive -Path $zipPath -DestinationPath $deployToolHome

          echo "home=$deployToolHome" >> $env:GITHUB_OUTPUT

      - name: Restore .NET Packages
        run: |
          dotnet tool restore
          dotnet restore

      - name: Update nuget-licenses.json
        run: dotnet tool run nuget-license -o JsonPretty -ji DragonFruit.OnionFruit.Windows/nuget-license-sources.json | Out-File -FilePath DragonFruit.OnionFruit/Assets/nuget-licenses.json -Encoding utf8
        continue-on-error: true

      - name: Run deployment tool
        run: dotnet ${{ steps.deploytool.outputs.home }}\DragonFruit.OnionFruit.Deploy.dll ${{ github.workspace }}\DragonFruit.OnionFruit.Windows\DragonFruit.OnionFruit.Windows.csproj ${{ matrix.rid }} "${{ github.event.inputs.version }}"
        env:
          ONIONDEPLOY_GitHub__User: ${{ github.repository_owner }}
          ONIONDEPLOY_GitHub__Repo: ${{ github.event.repository.name }}
          ONIONDEPLOY_GitHub__Token: ${{ github.token }}
          ONIONDEPLOY_Windows__CodeSigningPassword: ${{ secrets.CODESIGN_PASSWORD }}
          ONIONDEPLOY_Windows__CodeSigningCertificate: ${{ steps.import-cert.outputs.certPath }}

  build-macos:
    name: Build (${{ matrix.rid }})
    runs-on: macos-latest
    environment: release

    needs: [ create-draft-release ]

    strategy:
      matrix:
        rid: [osx-arm64, osx-x64]

    steps:
      - uses: actions/checkout@v4  
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
  
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
  
      - name: Install create-dmg
        run: NONINTERACTIVE=1 brew install create-dmg
  
      - name: Import Signing Certificate
        uses: apple-actions/import-codesign-certs@65cfbc37e1464d733524cb555b724878f278b8c3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
  
      - name: Setup Apple Notary Service
        env:
          NOTARY_EMAIL: ${{ secrets.APPLE_NOTARY_EMAIL }}
          NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
          NOTARY_TEAMID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcrun notarytool store-credentials "notarytool" \
            --apple-id "$NOTARY_EMAIL" \
            --team-id $NOTARY_TEAMID \
            --password $NOTARY_PASSWORD
  
      - id: deploytool
        name: Setup Deployment Tool
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          zipPath="$RUNNER_TEMP/onionfruit-deploy.zip"
          deployToolHome="$RUNNER_TEMP/onionfruit-deploy"
          
          # download, verify origin, extract deployment tool
          # curl -L -o "$zipPath" "https://github.com/dragonfruitnetwork/onionfruit-deploy/releases/latest/download/onionfruit-deploy.zip"
          
          curl -L -o "$zipPath" "https://github.com/dragonfruitnetwork/onionfruit-deploy/releases/download/1.1.1/onionfruit-deploy.zip"
          gh attestation verify "$zipPath" --repo dragonfruitnetwork/onionfruit-deploy --deny-self-hosted-runners
          
          unzip "$zipPath" -d "$deployToolHome"
          echo "home=$deployToolHome" >> "$GITHUB_OUTPUT"
  
      - name: Restore .NET Packages
        run: |
          dotnet tool restore
          dotnet restore
  
      - name: Update nuget-licenses.json
        run: dotnet tool run nuget-license -o JsonPretty -ji DragonFruit.OnionFruit.MacOS/nuget-license-sources.json > DragonFruit.OnionFruit/Assets/nuget-licenses.json
  
      - name: Build Native Components
        working-directory: ${{ github.workspace }}/macos-native
        run: |
          for i in "onionfruitd" "onionfruit";
          do
            xcodebuild -project onionfruit-osx.xcodeproj -configuration Release -scheme "$i" -sdk macosx ONLY_ACTIVE_ARCH=NO build
          done
  
      - name: Run deployment tool
        run: dotnet ${{ steps.deploytool.outputs.home }}/DragonFruit.OnionFruit.Deploy.dll ${{ github.workspace }}/DragonFruit.OnionFruit.MacOS/DragonFruit.OnionFruit.MacOS.csproj ${{ matrix.rid }} "${{ github.event.inputs.version }}"
        env:
          ONIONDEPLOY_GitHub__User: ${{ github.repository_owner }}
          ONIONDEPLOY_GitHub__Repo: ${{ github.event.repository.name }}
          ONIONDEPLOY_GitHub__Token: ${{ github.token }}
          ONIONDEPLOY_MacOS__CreateInstallDMG: true
          ONIONDEPLOY_MacOS__CodeSigningIdentity: ${{ secrets.APPLE_CERTIFICATE_IDENTITY }}
          ONIONDEPLOY_MacOS__NotaryKeychainProfile: notarytool

  copy-legacy:
    name: Copy legacy updater files
    runs-on: ubuntu-latest

    needs: [build-windows]
      
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
        - name: Download assets
          run: gh release download -p '*.nupkg' -p 'RELEASES' --repo dragonfruitnetwork/onionfruit

        - name: Re-upload assets
          run: gh release upload ${{ github.event.inputs.version }} *.nupkg RELEASES --repo dragonfruitnetwork/onionfruit
